name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: |
          apt-get update
          apt-get install -y ffmpeg
          apt-get clean

      - name: Install crunchy-cli
        run: |
          wget -q -O /usr/local/bin/crunchy $CRUNCHY_CLI_URL
          chmod +x /usr/local/bin/crunchy
        env:
          CRUNCHY_CLI_URL: https://github.com/crunchy-labs/crunchy-cli/releases/download/v3.0.0-dev.14/crunchy-v3.0.0-dev.14_linux

      - name: Log in
        run: crunchy login --credentials "$CRUNCHYROLL_USERNAME:$CRUNCHYROLL_PASSWORD"
        env: 
          CRUNCHYROLL_USERNAME: ${{ secrets.CRUNCHYROLL_USERNAME }}
          CRUNCHYROLL_PASSWORD: ${{ secrets.CRUNCHYROLL_PASSWORD }}

      - name: Download
        run: ./run.sh
        env:
          SHOWS: ${{ vars.SHOWS }}
